site_name: Boundless Exchange
theme: boundless
use_directory_urls: false
pages:
- Home: 'index.md'
- User Guide:
    - 'Accounts and Users': 'user-guide/accounts.md'
    - 'Content Discovery in Exchange': 'user-guide/discovery.md'
    - 'Working with  Documents': 'user-guide/documents.md'
    - 'Working with  Layers': 'user-guide/layers.md'
    - 'Working with  Maps': 'user-guide/maps.md'
    - 'Editing and Version Management': 'user-guide/editing.md'
    - 'Registry Layers': 'user-guide/registry.md'
    - 'Catalogue Service': 'user-guide/csw.md'
- About:
    - 'Release Notes': 'about/release.md'
    - 'License': 'about/license.md'
